import type { Metadata } from "next";
import { Inter, Lemonada } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const lemonada = Lemonada({ subsets: ["latin"], variable: "--font-lemonada" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${lemonada.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
